In [2]:
import pandas as pd
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler

In [3]:
stats= pd.read_csv("player_mvp_stats.csv")

In [4]:
stats

,Unnamed: 0,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,Pts Won,Share,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
0,0,Doc Rivers,PG,29,ATL,79,79,32.7,5.6,12.9,...,0.0,0.00,Atlanta Hawks,43,39,0.524,18.0,109.8,109.0,0.72
1,1,Dominique Wilkins,SF,31,ATL,81,81,38.0,9.5,20.2,...,29.0,0.03,Atlanta Hawks,43,39,0.524,18.0,109.8,109.0,0.72
2,2,Duane Ferrell,SF,25,ATL,78,2,14.9,2.2,4.6,...,0.0,0.00,Atlanta Hawks,43,39,0.524,18.0,109.8,109.0,0.72
3,3,Gary Leonard,C,23,ATL,4,0,2.3,0.0,0.0,...,0.0,0.00,Atlanta Hawks,43,39,0.524,18.0,109.8,109.0,0.72
4,4,John Battle,SG,28,ATL,79,2,23.6,5.0,10.9,...,0.0,0.00,Atlanta Hawks,43,39,0.524,18.0,109.8,109.0,0.72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15231,15231,Monte Morris,PG,27,WAS,62,61,27.3,4.0,8.3,...,0.0,0.00,Washington Wizards,35,47,0.427,9.0,113.2,114.4,-1.06
15232,15232,Quenton Jackson,PG,24,WAS,9,0,15.0,2.1,4.7,...,0.0,0.00,Washington Wizards,35,47,0.427,9.0,113.2,114.4,-1.06
15233,15233,Taj Gibson,C,37,WAS,49,2,9.8,1.3,2.6,...,0.0,0.00,Washington Wizards,35,47,0.427,9.0,113.2,114.4,-1.06
15234,15234,Vernon Carey Jr.,C,21,WAS,11,0,2.5,0.2,0.7,...,0.0,0.00,Washington Wizards,35,47,0.427,9.0,113.2,114.4,-1.06
15235,15235,Xavier Cooks,PF,27,WAS,10,1,12.6,1.7,2.8,...,0.0,0.00,Washington Wizards,35,47,0.427,9.0,113.2,114.4,-1.06

In [5]:
del stats["Unnamed: 0"]

In [6]:
stats

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,Pts Won,Share,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
0,Doc Rivers,PG,29,ATL,79,79,32.7,5.6,12.9,0.435,...,0.0,0.00,Atlanta Hawks,43,39,0.524,18.0,109.8,109.0,0.72
1,Dominique Wilkins,SF,31,ATL,81,81,38.0,9.5,20.2,0.470,...,29.0,0.03,Atlanta Hawks,43,39,0.524,18.0,109.8,109.0,0.72
2,Duane Ferrell,SF,25,ATL,78,2,14.9,2.2,4.6,0.489,...,0.0,0.00,Atlanta Hawks,43,39,0.524,18.0,109.8,109.0,0.72
3,Gary Leonard,C,23,ATL,4,0,2.3,0.0,0.0,NaN,...,0.0,0.00,Atlanta Hawks,43,39,0.524,18.0,109.8,109.0,0.72
4,John Battle,SG,28,ATL,79,2,23.6,5.0,10.9,0.461,...,0.0,0.00,Atlanta Hawks,43,39,0.524,18.0,109.8,109.0,0.72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15231,Monte Morris,PG,27,WAS,62,61,27.3,4.0,8.3,0.480,...,0.0,0.00,Washington Wizards,35,47,0.427,9.0,113.2,114.4,-1.06
15232,Quenton Jackson,PG,24,WAS,9,0,15.0,2.1,4.7,0.452,...,0.0,0.00,Washington Wizards,35,47,0.427,9.0,113.2,114.4,-1.06
15233,Taj Gibson,C,37,WAS,49,2,9.8,1.3,2.6,0.520,...,0.0,0.00,Washington Wizards,35,47,0.427,9.0,113.2,114.4,-1.06
15234,Vernon Carey Jr.,C,21,WAS,11,0,2.5,0.2,0.7,0.250,...,0.0,0.00,Washington Wizards,35,47,0.427,9.0,113.2,114.4,-1.06
15235,Xavier Cooks,PF,27,WAS,10,1,12.6,1.7,2.8,0.607,...,0.0,0.00,Washington Wizards,35,47,0.427,9.0,113.2,114.4,-1.06

In [7]:
pd.isnull(stats).sum()

Player        0
Pos           0
Age           0
Tm            0
G             0
GS            0
MP            0
FG            0
FGA           0
FG%          61
3P            0
3PA           0
3P%        2102
2P            0
2PA           0
2P%         105
eFG%         61
FT            0
FTA           0
FT%         545
ORB           0
DRB           0
TRB           0
AST           0
STL           0
BLK           0
TOV           0
PF            0
PTS           0
Year          0
Pts Won       0
Share         0
Team          0
W             0
L             0
W/L%          0
GB            0
PS/G          0
PA/G          0
SRS           0
dtype: int64

In [8]:
stats[pd.isnull(stats["3P%"])][["Player", "3PA"]]

                 Player  3PA
3          Gary Leonard  0.0
17         Gary Leonard  0.0
18         Jeff Sanders  0.0
34         Jeff Sanders  0.0
39         Randy Breuer  0.0
...                 ...  ...
15180    Daniel Gafford  0.0
15202   Jaime Echenique  0.0
15214  Vernon Carey Jr.  0.0
15218    Daniel Gafford  0.0
15234  Vernon Carey Jr.  0.0

[2102 rows x 2 columns]

In [9]:
stats[pd.isnull(stats["FT%"])][["Player", "FTA"]]

               Player  FTA
72        Tom Hovasse  0.0
87        Tim Kempton  0.0
89     Anthony Miller  0.0
148        Andy Panko  0.0
155        Ira Bowman  0.0
...               ...  ...
15203      Joel Ayayi  0.0
15204  Jordan Goodwin  0.0
15213  Tremont Waters  0.0
15221    Devon Dotson  0.0
15227  Jordan Schakel  0.0

[545 rows x 2 columns]

In [10]:
stats = stats.fillna(0)

In [11]:
stats.columns

Index(['Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year',
       'Pts Won', 'Share', 'Team', 'W', 'L', 'W/L%', 'GB', 'PS/G', 'PA/G',
       'SRS'],
      dtype='object')

In [12]:
predictors = ['Age',  'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year',
       'W', 'L', 'W/L%', 'GB', 'PS/G', 'PA/G',
       'SRS']

In [13]:
train = stats[stats["Year"] < 2023]
test = train = stats[stats["Year"] == 2023]

In [14]:
reg = Ridge(alpha=.1)

In [15]:
reg.fit(train[predictors] , train["Share"])

Ridge(alpha=0.1)

In [16]:
predictions = reg.predict(test[predictors])

In [17]:
predictions =pd.DataFrame(predictions,columns =["predictors"] , index=test.index)

In [18]:
predictions

       predictors
506     -0.019737
507     -0.020989
508     -0.032774
509     -0.008865
510      0.000276
...           ...
15231   -0.019531
15232   -0.001745
15233   -0.018148
15234   -0.004714
15235   -0.024454

[539 rows x 1 columns]

In [19]:
combantion = pd.concat([test[["Player" , "Share"]],predictions],axis =1 )

In [20]:
combantion

                  Player  Share  predictors
506           AJ Griffin    0.0   -0.019737
507        Aaron Holiday    0.0   -0.020989
508    Bogdan Bogdanović    0.0   -0.032774
509       Bruno Fernando    0.0   -0.008865
510         Clint Capela    0.0    0.000276
...                  ...    ...         ...
15231       Monte Morris    0.0   -0.019531
15232    Quenton Jackson    0.0   -0.001745
15233         Taj Gibson    0.0   -0.018148
15234   Vernon Carey Jr.    0.0   -0.004714
15235       Xavier Cooks    0.0   -0.024454

[539 rows x 3 columns]

In [21]:
combantion.sort_values("Share",ascending = False).head(10)

                        Player  Share  predictors
11333              Joel Embiid  0.915    0.207448
3821              Nikola Jokić  0.674    0.173088
8327     Giannis Antetokounmpo  0.606    0.256396
1031              Jayson Tatum  0.280    0.122173
10296  Shai Gilgeous-Alexander  0.046    0.097225
2763          Donovan Mitchell  0.030    0.031647
12843         Domantas Sabonis  0.027    0.103617
3302               Luka Dončić  0.010    0.165915
4855             Stephen Curry  0.005    0.029885
7820              Jimmy Butler  0.003    0.077268

In [22]:
mean_squared_error(combantion["Share"],combantion["predictors"])

0.0022788441889804788

In [23]:
combantion["Share"].value_counts()

Share
0.000    526
0.001      2
0.280      1
0.030      1
0.010      1
0.674      1
0.005      1
0.003      1
0.606      1
0.046      1
0.915      1
0.002      1
0.027      1
Name: count, dtype: int64

In [24]:
actuel_vote = combantion.sort_values("Share",ascending = False)

In [25]:
actuel_vote["Rk"]= list(range(1,actuel_vote.shape[0] +1))

In [26]:
actuel_vote.head(20)

                        Player  Share  predictors  Rk
11333              Joel Embiid  0.915    0.207448   1
3821              Nikola Jokić  0.674    0.173088   2
8327     Giannis Antetokounmpo  0.606    0.256396   3
1031              Jayson Tatum  0.280    0.122173   4
10296  Shai Gilgeous-Alexander  0.046    0.097225   5
2763          Donovan Mitchell  0.030    0.031647   6
12843         Domantas Sabonis  0.027    0.103617   7
3302               Luka Dončić  0.010    0.165915   8
4855             Stephen Curry  0.005    0.029885   9
7820              Jimmy Butler  0.003    0.077268  10
12841             De'Aaron Fox  0.002    0.076221  11
10032            Jalen Brunson  0.001    0.019007  12
7287                 Ja Morant  0.001    0.086370  13
10795                  Bol Bol  0.000    0.019199  14
10292         Lindy Waters III  0.000   -0.004139  15
10297                 Tre Mann  0.000   -0.016836  16
10796            Caleb Houstan  0.000   -0.025657  17
10295            Ousmane Dieng  0.000   -0.007945  18
10294             Olivier Sarr  0.000   -0.020735  19
10797              Chuma Okeke  0.000   -0.019284  20

In [27]:
actuel_vote = actuel_vote.sort_values("predictors",ascending = False)

In [28]:
actuel_vote["Predicted_Rk"]= list(range(1,actuel_vote.shape[0] +1))

In [29]:
actuel_vote.head(20)

                        Player  Share  predictors   Rk  Predicted_Rk
8327     Giannis Antetokounmpo  0.606    0.256396    3             1
11333              Joel Embiid  0.915    0.207448    1             2
3821              Nikola Jokić  0.674    0.173088    2             3
3302               Luka Dončić  0.010    0.165915    8             4
1031              Jayson Tatum  0.280    0.122173    4             5
9506           Zion Williamson  0.000    0.112168  114             6
11839             Kevin Durant  0.000    0.105078  234             7
12843         Domantas Sabonis  0.027    0.103617    7             8
6913             Anthony Davis  0.000    0.103329  415             9
10035            Julius Randle  0.000    0.097485   73            10
10296  Shai Gilgeous-Alexander  0.046    0.097225    5            11
7287                 Ja Morant  0.001    0.086370   13            12
12332           Damian Lillard  0.000    0.084359  225            13
7820              Jimmy Butler  0.003    0.077268   10            14
12841             De'Aaron Fox  0.002    0.076221   11            15
5884              Myles Turner  0.000    0.073684  438            16
11332             James Harden  0.000    0.070760   54            17
6920              LeBron James  0.000    0.069237  441            18
8839               Rudy Gobert  0.000    0.066950  132            19
1030              Jaylen Brown  0.000    0.065985  351            20

In [30]:
actuel_vote.sort_values("Share",ascending = False).head(10)

                        Player  Share  predictors  Rk  Predicted_Rk
11333              Joel Embiid  0.915    0.207448   1             2
3821              Nikola Jokić  0.674    0.173088   2             3
8327     Giannis Antetokounmpo  0.606    0.256396   3             1
1031              Jayson Tatum  0.280    0.122173   4             5
10296  Shai Gilgeous-Alexander  0.046    0.097225   5            11
2763          Donovan Mitchell  0.030    0.031647   6            59
12843         Domantas Sabonis  0.027    0.103617   7             8
3302               Luka Dončić  0.010    0.165915   8             4
4855             Stephen Curry  0.005    0.029885   9            62
7820              Jimmy Butler  0.003    0.077268  10            14

In [31]:
def find_ap(actuel_vote):
    real = actuel_vote.sort_values("Share", ascending=False).head(5)
    predicted = actuel_vote.sort_values("predictors", ascending=False)

    ps = []
    found = 0
    seen = 1
    
    for index, row in predicted.iterrows():
        if row["Player"] in real["Player"].values:
            found += 1
            ps.append(found / seen)
        seen += 1
    
    return sum(ps)/ len(ps)

In [32]:
find_ap(actuel_vote)

0.8509090909090908

In [33]:
years = list(range(1991,2024))

In [34]:
aps = []
all_prediction =[]
for year in years[5:]:
    train = stats[stats["Year"] < year]
    test = stats[stats["Year"] == year]
    reg.fit(train[predictors] , train["Share"])
    predictions = reg.predict(test[predictors])
    predictions =pd.DataFrame(predictions,columns =["predictors"] , index=test.index)
    combantion = pd.concat([test[["Player" , "Share"]],predictions],axis =1 )
    all_prediction.append(combantion)
    aps.append(find_ap(combantion))

In [35]:
sum(aps)/ len(aps)

0.7195472452665953

In [36]:
def add_ranks(df):
    df = df.sort_values("Share",ascending = False)
    df["Rk"]= list(range(1,df.shape[0] +1))
    df = df.sort_values("predictors",ascending = False)
    df["Predicted_Rk"]= list(range(1,df.shape[0] +1))
    df["Difference"] = df["Rk"]-df["Predicted_Rk"]
    return df

In [37]:
ranking = add_ranks(all_prediction[0])
ranking[ranking["Rk"] <6].sort_values("Difference", ascending = False)

                  Player  Share  predictors  Rk  Predicted_Rk  Difference
4932     Hakeem Olajuwon  0.211    0.204628   4             3           1
12936     David Robinson  0.508    0.211326   2             2           0
1806      Michael Jordan  0.986    0.174346   1             5          -4
10370  Anfernee Hardaway  0.319    0.096954   3            12          -9
1809      Scottie Pippen  0.200    0.066921   5            20         -15

In [38]:
all_prediction[0].sort_values("Share", ascending = False)

                  Player  Share  predictors
1806      Michael Jordan  0.986    0.174346
12936     David Robinson  0.508    0.211326
10370  Anfernee Hardaway  0.319    0.096954
4932     Hakeem Olajuwon  0.211    0.204628
1809      Scottie Pippen  0.200    0.066921
...                  ...    ...         ...
4934       Jaren Jackson  0.000    0.036886
4933         Henry James  0.000   -0.008417
4931   Eldridge Recasner  0.000   -0.021411
4930       Clyde Drexler  0.000    0.072601
14790         Tim Legler  0.000   -0.022825

[428 rows x 3 columns]

In [39]:
def backtest(stats, model, years, predictors):
    aps = []
    all_predictions = []
    years = list(range(1991,2023))
    for year in years[5:]:
        # Split data into training and testing sets
        train = stats[stats["Year"] < year]
        test = stats[stats["Year"] == year]

        # Fit the model on training data
        model.fit(train[predictors], train["Share"])

        # Predict on testing data
        predictions = model.predict(test[predictors])
        predictions_df = pd.DataFrame(predictions, columns=["predictors"], index=test.index)

        # Combine predictions with test data
        combination = pd.concat([test[["Player", "Share"]], predictions_df], axis=1)
        combination = add_ranks(combination)

        # Collect results
        all_predictions.append(combination)
        aps.append(find_ap(combination))

    # Return average performance, all performance metrics, and concatenated results
    return sum(aps) / len(aps), aps, pd.concat(all_predictions)

In [40]:
mean_ap , aps,all_prediction = backtest(stats ,reg,years[5:] ,predictors)

In [41]:
mean_ap

0.7152712173135063

In [42]:
all_prediction[all_prediction["Rk"] <=5].sort_values("Difference").head(10)

                 Player  Share  predictors  Rk  Predicted_Rk  Difference
9018         Jason Kidd  0.712    0.028210   2            52         -50
1493          Glen Rice  0.117    0.033110   5            53         -48
11555        Steve Nash  0.839    0.034100   1            45         -44
12546   Peja Stojaković  0.228    0.036270   4            38         -34
2073        Joakim Noah  0.258    0.046968   4            37         -33
11573        Steve Nash  0.739    0.054129   1            34         -33
4050   Chauncey Billups  0.344    0.052696   5            35         -30
11793        Chris Paul  0.138    0.072293   5            33         -28
11588        Steve Nash  0.785    0.074421   2            21         -19
7397       Tim Hardaway  0.207    0.059984   4            20         -16

In [43]:
pd.concat([pd.Series(reg.coef_), pd.Series(predictors)], axis=1).sort_values(0, ascending=False)

           0     1
13  0.087853  eFG%
18  0.033860   DRB
29  0.023202  W/L%
17  0.020993   ORB
10  0.016456    2P
21  0.012070   STL
22  0.010901   BLK
15  0.010414   FTA
20  0.007113   AST
12  0.007052   2P%
25  0.006918   PTS
5   0.004827   FGA
4   0.003352    FG
7   0.001701    3P
0   0.000294   Age
30  0.000279    GB
27  0.000136     W
1   0.000093     G
2   0.000004    GS
26 -0.000180  Year
32 -0.000275  PA/G
28 -0.000316     L
31 -0.000494  PS/G
33 -0.000569   SRS
24 -0.002624    PF
3  -0.004067    MP
16 -0.004783   FT%
14 -0.006344    FT
23 -0.009143   TOV
8  -0.009681   3PA
9  -0.009694   3P%
11 -0.016464   2PA
19 -0.026578   TRB
6  -0.155934   FG%

In [44]:
stat_ratios = stats[["PTS", "AST", "STL", "BLK", "3P", "Year"]].groupby("Year").apply(lambda x: x/x.mean())

C:\Users\wwera\AppData\Local\Temp\ipykernel_7728\3437527063.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stat_ratios = stats[["PTS", "AST", "STL", "BLK", "3P", "Year"]].groupby("Year").apply(lambda x: x/x.mean())

In [45]:
stat_ratios

                 PTS       AST       STL       BLK        3P  Year
Year
1991 0      1.692601  2.010078  2.608773  1.346939  5.594452   1.0
     1      2.884104  1.542618  2.059558  1.795918  5.085865   1.0
     2      0.679268  0.327222  0.549215  0.673469  0.000000   1.0
     3      0.055678  0.000000  0.000000  0.673469  0.000000   1.0
     4      1.514433  1.262142  0.823823  0.224490  1.017173   1.0
...              ...       ...       ...       ...       ...   ...
2023 15231  1.129221  2.561833  1.148205  0.523047  1.312418   1.0
     15232  0.679725  0.821720  0.656117  0.261524  0.100955   1.0
     15233  0.372752  0.338355  0.492088  0.523047  0.201910   1.0
     15234  0.054817  0.145009  0.328058  0.523047  0.000000   1.0
     15235  0.416606  0.290019  0.984175  1.046094  0.000000   1.0

[15236 rows x 6 columns]

In [46]:
# Reset index to ensure alignment
stats_reset = stats.reset_index(drop=True)
stat_ratios_reset = stat_ratios.reset_index(drop=True)

# Add new columns from stat_ratios
stats_reset["PTS_R"] = stat_ratios_reset["PTS"]
stats_reset["AST_R"] = stat_ratios_reset["AST"]
stats_reset["STL_R"] = stat_ratios_reset["STL"]
stats_reset["BLK_R"] = stat_ratios_reset["BLK"]
stats_reset["3P_R"] = stat_ratios_reset["3P"]

In [47]:
stats_reset.head()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,W/L%,GB,PS/G,PA/G,SRS,PTS_R,AST_R,STL_R,BLK_R,3P_R
0,Doc Rivers,PG,29,ATL,79,79,32.7,5.6,12.9,0.435,...,0.524,18.0,109.8,109.0,0.72,1.692601,2.010078,2.608773,1.346939,5.594452
1,Dominique Wilkins,SF,31,ATL,81,81,38.0,9.5,20.2,0.470,...,0.524,18.0,109.8,109.0,0.72,2.884104,1.542618,2.059558,1.795918,5.085865
2,Duane Ferrell,SF,25,ATL,78,2,14.9,2.2,4.6,0.489,...,0.524,18.0,109.8,109.0,0.72,0.679268,0.327222,0.549215,0.673469,0.000000
3,Gary Leonard,C,23,ATL,4,0,2.3,0.0,0.0,0.000,...,0.524,18.0,109.8,109.0,0.72,0.055678,0.000000,0.000000,0.673469,0.000000
4,John Battle,SG,28,ATL,79,2,23.6,5.0,10.9,0.461,...,0.524,18.0,109.8,109.0,0.72,1.514433,1.262142,0.823823,0.224490,1.017173

In [48]:
player_rows = stats_reset[stats_reset['Player'] == "James Worthy"]
player_rows

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,W/L%,GB,PS/G,PA/G,SRS,PTS_R,AST_R,STL_R,BLK_R,3P_R
6421,James Worthy,SF,29,LAL,78,74,38.6,9.2,18.7,0.492,...,0.707,5.0,106.3,99.6,6.73,1.991903,3.729835,1.988423,0.756192,3.474633
6436,James Worthy,SF,30,LAL,54,54,39.0,8.3,18.6,0.447,...,0.524,14.0,100.4,101.5,-0.95,0.162860,0.177611,0.165702,0.756192,0.217165
6453,James Worthy,SF,31,LAL,82,69,28.8,6.2,13.9,0.447,...,0.476,23.0,104.2,105.5,-1.20,2.142236,2.249741,2.154124,0.756192,4.560455
6464,James Worthy,SF,32,LAL,80,2,20.0,4.3,10.5,0.406,...,0.402,30.0,100.4,104.7,-3.93,0.450997,0.236815,0.331404,0.756192,1.520152

In [49]:
normalized_predictors = predictors.copy()
normalized_predictors += ["PTS_R", "AST_R", "STL_R", "BLK_R", "3P_R"]

In [50]:
normalized_predictors

['Age',
 'G',
 'GS',
 'MP',
 'FG',
 'FGA',
 'FG%',
 '3P',
 '3PA',
 '3P%',
 '2P',
 '2PA',
 '2P%',
 'eFG%',
 'FT',
 'FTA',
 'FT%',
 'ORB',
 'DRB',
 'TRB',
 'AST',
 'STL',
 'BLK',
 'TOV',
 'PF',
 'PTS',
 'Year',
 'W',
 'L',
 'W/L%',
 'GB',
 'PS/G',
 'PA/G',
 'SRS',
 'PTS_R',
 'AST_R',
 'STL_R',
 'BLK_R',
 '3P_R']

In [51]:
mean_ap , aps,all_prediction = backtest(stats_reset ,reg,years[5:] ,normalized_predictors)

In [52]:
mean_ap

0.7082228636030473

In [53]:
stats_reset["Npos"] =stats_reset["Pos"].astype("category").cat.codes
stats_reset["NTm"] =stats_reset["Tm"].astype("category").cat.codes

In [54]:
stats_reset["Pos"].unique()

array(['PG', 'SF', 'C', 'SG', 'PF', 'PF-SF', 'PG-SG', 'C-PF', 'SG-SF',
       'SG-PG', 'PF-C', 'SF-SG', 'SF-PF', 'SG-PF', 'SF-C', 'PG-SF',
       'SG-PG-SF'], dtype=object)

In [55]:
stats_reset.head()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,PS/G,PA/G,SRS,PTS_R,AST_R,STL_R,BLK_R,3P_R,Npos,NTm
0,Doc Rivers,PG,29,ATL,79,79,32.7,5.6,12.9,0.435,...,109.8,109.0,0.72,1.692601,2.010078,2.608773,1.346939,5.594452,5,0
1,Dominique Wilkins,SF,31,ATL,81,81,38.0,9.5,20.2,0.470,...,109.8,109.0,0.72,2.884104,1.542618,2.059558,1.795918,5.085865,8,0
2,Duane Ferrell,SF,25,ATL,78,2,14.9,2.2,4.6,0.489,...,109.8,109.0,0.72,0.679268,0.327222,0.549215,0.673469,0.000000,8,0
3,Gary Leonard,C,23,ATL,4,0,2.3,0.0,0.0,0.000,...,109.8,109.0,0.72,0.055678,0.000000,0.000000,0.673469,0.000000,0,0
4,John Battle,SG,28,ATL,79,2,23.6,5.0,10.9,0.461,...,109.8,109.0,0.72,1.514433,1.262142,0.823823,0.224490,1.017173,12,0

In [56]:
stats_reset["Npos"].unique()

array([ 5,  8,  0, 12,  2,  4,  7,  1, 16, 14,  3, 11, 10, 13,  9,  6, 15],
      dtype=int8)

In [57]:
stats_reset["NTm"].unique()

array([ 0,  1,  2,  3,  4,  6,  5,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 23, 22, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 37, 36], dtype=int8)

In [58]:
stats_reset["NTm"].value_counts()

NTm
7     539
8     535
27    532
17    529
14    528
11    525
0     524
12    520
1     519
31    518
9     517
15    513
26    513
13    512
18    512
5     510
29    506
30    506
10    505
34    505
24    503
28    502
19    500
33    460
36    431
16    371
20    343
32    263
25    256
2     202
23    179
4     177
3     157
6     147
21    143
37    114
35     88
22     32
Name: count, dtype: int64

In [59]:
 rf = RandomForestRegressor(n_estimators=50, random_state=1, min_samples_split=5)

In [60]:
stats_reset.columns

Index(['Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year',
       'Pts Won', 'Share', 'Team', 'W', 'L', 'W/L%', 'GB', 'PS/G', 'PA/G',
       'SRS', 'PTS_R', 'AST_R', 'STL_R', 'BLK_R', '3P_R', 'Npos', 'NTm'],
      dtype='object')

In [61]:
Random_predictors = normalized_predictors.copy()
Random_predictors += ["Npos", "NTm"]

In [62]:
predictors= Random_predictors.copy()

In [171]:
 mean_ap , aps,all_prediction = backtest(stats_reset,rf,years[28:] ,predictors)

In [172]:
mean_ap

0.701954274470308

In [177]:
all_prediction

                 Player  Share  predictors   Rk  Predicted_Rk  Difference
1806     Michael Jordan  0.986    0.705792    1             1           0
10384  Shaquille O'Neal  0.056    0.567282    9             2           7
14184       Karl Malone  0.075    0.323130    7             3           4
12936    David Robinson  0.508    0.321031    2             4          -2
4932    Hakeem Olajuwon  0.211    0.285350    4             5          -1
...                 ...    ...         ...  ...           ...         ...
13343      Jock Landale  0.000    0.000000  252           601        -349
11822    Justin Jackson  0.000    0.000000  251           602        -351
11824       M.J. Walker  0.000    0.000000  250           603        -353
12319    Greg Brown III  0.000    0.000000  249           604        -355
15214  Vernon Carey Jr.  0.000    0.000000  605           605           0

[12728 rows x 6 columns]

In [179]:
data = all_prediction[all_prediction['Player'] == 'Nikola Jokić']

In [181]:
data

            Player  Share  predictors   Rk  Predicted_Rk  Difference
3701  Nikola Jokić  0.000    0.000000  419           199         220
3716  Nikola Jokić  0.000    0.000607  445            53         392
3729  Nikola Jokić  0.000    0.051102  504            15         489
3748  Nikola Jokić  0.210    0.027224    4            21         -17
3763  Nikola Jokić  0.018    0.020834    9            25         -16
3783  Nikola Jokić  0.961    0.145159    1            12         -11
3805  Nikola Jokić  0.875    0.359810    1             3          -2

In [183]:
predictors

['Age',
 'G',
 'GS',
 'MP',
 'FG',
 'FGA',
 'FG%',
 '3P',
 '3PA',
 '3P%',
 '2P',
 '2PA',
 '2P%',
 'eFG%',
 'FT',
 'FTA',
 'FT%',
 'ORB',
 'DRB',
 'TRB',
 'AST',
 'STL',
 'BLK',
 'TOV',
 'PF',
 'PTS',
 'Year',
 'W',
 'L',
 'W/L%',
 'GB',
 'PS/G',
 'PA/G',
 'SRS',
 'PTS_R',
 'AST_R',
 'STL_R',
 'BLK_R',
 '3P_R',
 'Npos',
 'NTm']

In [185]:
sc = StandardScaler()

In [187]:
def sc_backtest(stats, model, years, predictors):
    aps = []
    all_predictions = []
    for year in years:
        train = stats[stats["Year"] < year].copy()
        test = stats[stats["Year"] == year].copy()
        sc.fit(train[predictors])
        train[predictors] = sc.transform(train[predictors])
        test[predictors] = sc.transform(test[predictors])
        model.fit(train[predictors],train["Share"])
        predictions = model.predict(test[predictors])
        predictions = pd.DataFrame(predictions, columns=["predictors"], index=test.index)
        combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)
        combination = add_ranks(combination)
        all_predictions.append(combination)
        aps.append(find_ap(combination))
    return sum(aps) / len(aps), aps, pd.concat(all_predictions)

In [189]:
mean_ap, aps, all_predictions = sc_backtest(stats_reset, reg, years[28:], predictors)

In [191]:
mean_ap

0.8050649350649349

In [193]:
data = all_prediction[all_prediction['Player'] == 'Nikola Jokić']

In [195]:
data

            Player  Share  predictors   Rk  Predicted_Rk  Difference
3701  Nikola Jokić  0.000    0.000000  419           199         220
3716  Nikola Jokić  0.000    0.000607  445            53         392
3729  Nikola Jokić  0.000    0.051102  504            15         489
3748  Nikola Jokić  0.210    0.027224    4            21         -17
3763  Nikola Jokić  0.018    0.020834    9            25         -16
3783  Nikola Jokić  0.961    0.145159    1            12         -11
3805  Nikola Jokić  0.875    0.359810    1             3          -2

In [197]:
sc.transform(stats_reset[predictors])

array([[ 0.53021954,  1.05192322,  1.83612066, ...,  3.66710219,
        -0.08216202, -1.71642013],
       [ 1.00165961,  1.13160105,  1.90492249, ...,  3.26109654,
         0.60962879, -1.71642013],
       [-0.41266061,  1.01208431, -0.81274964, ..., -0.79896001,
         0.60962879, -1.71642013],
       ...,
       [ 2.41597983, -0.14324425, -0.81274964, ..., -0.63777447,
        -1.23514672,  1.70293983],
       [-1.35554075, -1.65712306, -0.88155147, ..., -0.79896001,
        -1.23514672,  1.70293983],
       [ 0.05877946, -1.69696197, -0.84715056, ..., -0.79896001,
        -0.77395284,  1.70293983]])

In [211]:
filtered_data = all_prediction[(all_prediction['Rk'] == 1) & (all_prediction['Difference'] == 0)]


filtered_data

                      Player  Share  predictors  Rk  Predicted_Rk  Difference
1806          Michael Jordan  0.986    0.705792   1             1           0
1834          Michael Jordan  0.934    0.742358   1             1           0
14220            Karl Malone  0.701    0.195177   1             1           0
6554        Shaquille O'Neal  0.998    0.680121   1             1           0
10967          Allen Iverson  0.904    0.478261   1             1           0
13044             Tim Duncan  0.808    0.355973   1             1           0
8536           Kevin Garnett  0.991    0.442417   1             1           0
2535            LeBron James  0.980    0.676923   1             1           0
7632            LeBron James  0.888    0.462713   1             1           0
7648            LeBron James  0.998    0.656271   1             1           0
10127           Kevin Durant  0.986    0.725661   1             1           0
4739           Stephen Curry  1.000    0.828251   1             1           0
5274            James Harden  0.955    0.682942   1             1           0
8277   Giannis Antetokounmpo  0.952    0.729444   1             1           0

In [213]:
row_count = filtered_data.shape[0]

In [215]:
row_count

14

In [201]:
mean_ap, aps, all_predictions = sc_backtest(stats_reset, rf, years[28:], predictors)

In [203]:
mean_ap

0.8512175324675324

In [205]:

filtered_data = all_prediction[(all_prediction['Rk'] == 1) & (all_prediction['Difference'] == 0)]


filtered_data

                      Player  Share  predictors  Rk  Predicted_Rk  Difference
1806          Michael Jordan  0.986    0.705792   1             1           0
1834          Michael Jordan  0.934    0.742358   1             1           0
14220            Karl Malone  0.701    0.195177   1             1           0
6554        Shaquille O'Neal  0.998    0.680121   1             1           0
10967          Allen Iverson  0.904    0.478261   1             1           0
13044             Tim Duncan  0.808    0.355973   1             1           0
8536           Kevin Garnett  0.991    0.442417   1             1           0
2535            LeBron James  0.980    0.676923   1             1           0
7632            LeBron James  0.888    0.462713   1             1           0
7648            LeBron James  0.998    0.656271   1             1           0
10127           Kevin Durant  0.986    0.725661   1             1           0
4739           Stephen Curry  1.000    0.828251   1             1           0
5274            James Harden  0.955    0.682942   1             1           0
8277   Giannis Antetokounmpo  0.952    0.729444   1             1           0

In [207]:
row_count = filtered_data.shape[0]

In [209]:
row_count

14